Allow user change email
ITI/searcch-backend pull request #96
Opened 2023-02-21 17:34 UTC by ckouder

This pull request addresses issue https://github.com/ITI/searcch/issues/155, tested with Google login and github login, haven't tested with cilogon but it should work

2023-02-21 21:54 UTC, carboxylman commented on searcch_backend/api/resources/login.py
> +            (user_email, user_name, idp_uid) = self._validate_token(strategy, sso_token)
Let's make sure that the third element of the tuple returned from _validate_token() is stringified, or None.

2023-02-21 22:42 UTC, carboxylman requested changes

2023-02-21 22:42 UTC, carboxylman commented on searcch_backend/api/resources/login.py
> +                setattr(idp_credential, strategy + '_id', idp_uid)
Let's be careful to insert only strings here.

2023-02-21 22:42 UTC, carboxylman commented on searcch_backend/api/resources/login.py
> +                        person.email = user_email
Can we please add a DEBUG log statement here, for ease of observability with testing?

2023-02-21 22:42 UTC, carboxylman commented on searcch_backend/api/resources/login.py
> -            else:  # create new user
Let's leave comments in even if badly formatted, unless they are wrong, which I think this one is not?

2023-02-21 22:42 UTC, carboxylman commented on searcch_backend/migrations/versions/f29a393d7f66_add_user_ipd_credential_table.py
> +    op.create_table('user_idp_credentials',
On the call I suggested that we do something more general, but on further reflection this is good for right now.  Sorry.

2023-02-24 20:03 UTC, carboxylman approved these changes

2023-02-24 20:04 UTC, merged

2023-02-25 00:17 UTC, carboxylman commented
@ckouder I added fixes for the existing-user, no-idp_credential case: https://github.com/ITI/searcch-backend/commit/a42631de472e538d6f67343bbfaf12baab32ee1b

2023-02-25 03:14 UTC, ckouder commented
> @ckouder I added fixes for the existing-user, no-idp_credential case: [a42631d](https://github.com/ITI/searcch-backend/commit/a42631de472e538d6f67343bbfaf12baab32ee1b)

thank you!